image: docker:git

default:
  tags:
  - docker
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker buildx create --driver docker-container --bootstrap --use

stages:
- build-and-push

build-and-push-job:
  timeout: 3h
  stage: build-and-push
  script:
  - cd $CI_PROJECT_DIR && docker buildx build -f Dockerfile --push --provenance=false --platform linux/amd64 --build-arg REPO_NAME=$CI_PROJECT_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
  rules:
    - changes:
        - pyproject.toml
        - .gitlab-ci.yml
        - Dockerfile
