apiVersion: batch/v1
kind: Job

metadata:
  labels:
    app: k8s-setup-template
  name: viyer9-test

spec:
  template:
    spec:
      containers:
      - name: template-runner
        image: gitlab-registry.nrp-nautilus.io/varuniyer/k8s-setup-template:latest
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: viyer9-gitlab
              key: user
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: viyer9-gitlab
              key: password
        
        command: ["bash", "-c"]
        args:
        - |
          cd k8s-setup-template
          python test_script.py
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - -b
          - main
          - --single-branch
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/varuniyer/k8s-setup-template
          - /home/user/work/k8s-setup-template
        volumeMounts:
          - name: git-repo
            mountPath: /home/user/work
      volumes:
      - name: git-repo
        emptyDir: {}

      imagePullSecrets:
      - name: viyer9-k8s-setup-template-regcred

      restartPolicy: Never
  
  backoffLimit: 0
