apiVersion: batch/v1
kind: Job

metadata:
  labels:
    app: "{repo}"
  name: "{netid}-{repo_lower}"

spec:
  template:
    spec:
      containers:
      - name: "{repo_lower}-runner"
        image: "{registry_server}/{username}/{repo_lower}:latest"
        command: ["bash", "-i", "run.sh"]
        workingDir: "/home/user/work/{repo}"
        volumeMounts:
          - name: git-repo
            mountPath: /home/user/work/{repo}
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        env:
        - name: GITLAB_PAT
          valueFrom:
            secretKeyRef:
              name: "{gitlab_secret}"
              key: pat
        args:
          - clone
          - -b
          - {branch}
          - --single-branch
          - https://{username}:$(GITLAB_PAT)@gitlab.nrp-nautilus.io/{username}/{repo}.git
          - /opt/{repo}
        resources:
          limits:
            memory: 100Mi
            cpu: "100m"
            ephemeral-storage: 100Mi
          requests:
            memory: 100Mi
            cpu: "100m"
            ephemeral-storage: 100Mi
        volumeMounts:
          - name: git-repo
            mountPath: /opt/{repo}
      volumes:
      - name: git-repo
        emptyDir: {{}}

      imagePullSecrets:
      - name: "{registry_secret}"

      restartPolicy: Never
  
  backoffLimit: 0 
