apiVersion: batch/v1
kind: Job

metadata:
  labels:
    app: "{repo}"
  name: "{netid}-{repo_lower}"

spec:
  template:
    spec:
      securityContext:
        fsGroup: 1000

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090

      containers:
      - name: "{repo_lower}-runner"
        image: "{registry_server}/{username}/{repo_lower}:latest"
        workingDir: "/home/ubuntu/work/{repo}"

        env:
        - name: "MY_ENV_VAR"
          value: "my_value"

        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi

        volumeMounts:
          - name: dshm
            mountPath: "/dev/shm"
          - name: git-repo
            mountPath: "/home/ubuntu/work/{repo}"

      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: git-repo
        emptyDir: {{}}

      initContainers:
      - name: init-clone-repo
        image: alpine/git
        env:
        - name: GITLAB_PAT
          valueFrom:
            secretKeyRef:
              name: "{gitlab_secret}"
              key: pat
        args:
          - clone
          - -b
          - "{branch}"
          - --single-branch
          - https://{username}:$(GITLAB_PAT)@gitlab.nrp-nautilus.io/{username}/{repo}.git
          - "/opt/{repo}"
        resources:
          limits:
            memory: 500Mi
            cpu: "500m"
            ephemeral-storage: 500Mi
          requests:
            memory: 500Mi
            cpu: "500m"
            ephemeral-storage: 500Mi
        volumeMounts:
          - name: git-repo
            mountPath: "/opt/{repo}"

      imagePullSecrets:
      - name: "{registry_secret}"

      restartPolicy: Never
  
  backoffLimit: 0 
