apiVersion: batch/v1
kind: Job

metadata:
  labels:
    app: "{repo_name}"
  name: "{netid}-test"

spec:
  template:
    spec:
      containers:
      - name: template-runner
        image: gitlab-registry.nrp-nautilus.io/{gitlab_username}/{repo_name_lower}:latest
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: "{netid}-gitlab"
              key: user
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{netid}-gitlab"
              key: password
        
        command: ["bash", "-c"]
        args:
        - |
          cd {repo_name}
          python test_script.py
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - -b
          - {branch_name}
          - --single-branch
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/{gitlab_username}/{repo_name}
          - /home/user/work/{repo_name}
        volumeMounts:
          - name: git-repo
            mountPath: /home/user/work
      volumes:
      - name: git-repo
        emptyDir: {{}}

      imagePullSecrets:
      - name: "{netid}-{repo_name_lower}-regcred"

      restartPolicy: Never
  
  backoffLimit: 0 