apiVersion: batch/v1
kind: Job

metadata:
  labels:
    app: "{repo}"
  name: "{netid}-{repo_lower}"

spec:
  template:
    spec:
      containers:
      - name: template-runner
        image: gitlab-registry.nrp-nautilus.io/{username}/{repo_lower}:latest
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: "{netid}-gitlab"
              key: user
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{netid}-gitlab"
              key: password
        
        command: ["bash", "/home/user/work/{repo}/run.sh"]
        workingDir: "/home/user/work/{repo}"
        volumeMounts:
          - name: git-repo
            mountPath: /home/user/work/{repo}
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
          requests:
            nvidia.com/gpu: "1"
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 4Gi
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - -b
          - {branch}
          - --single-branch
          - https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/{username}/{repo}
          - /opt/{repo}
        resources:
          limits:
            memory: 100Mi
            cpu: "100m"
          requests:
            memory: 100Mi
            cpu: "100m"
        volumeMounts:
          - name: git-repo
            mountPath: /opt/{repo}
      volumes:
      - name: git-repo
        emptyDir: {{}}

      imagePullSecrets:
      - name: "{netid}-{repo_lower}-regcred"

      restartPolicy: Never
  
  backoffLimit: 0 
